name = "ConstrainedDynamics"
uuid = "65b0d8a9-e9fd-4f02-8653-a7163c490b26"
authors = ["Jan Bruedigam"]
version = "0.5.5"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Colors = "<0.12.4, 0.12.4"
ForwardDiff = "<0.10.12,0.10.12"
LightXML = "<0.9.0, 0.9.0"
Rotations = "1.0.0, 1.0.1"
StaticArrays = "0.12.0, 0.12.4"
julia = "1.2, 1.5"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "ForwardDiff", "BenchmarkTools"]
