name = "ConstrainedDynamics"
uuid = "65b0d8a9-e9fd-4f02-8653-a7163c490b26"
authors = ["Jan Bruedigam"]
version = "0.1.0"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Blink = "0.12.3"
Colors = "0.11.2"
CoordinateTransformations = "0.5.1"
FileIO = "1.2.4"
GeometryTypes = "0.7.10"
LightXML = "0.9.0"
MeshCat = "0.9.1"
MeshIO = "0.3.2"
Plots = "1.0.12"
Rotations = "0.13.0"
StaticArrays = "0.12.1"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
